### ISSUE TITLE
Jaeger exporter not working with collector

### ISSUE THREAD

**Issue by 23doors** [census-instrumentation/opencensus-python#878]
**Describe your environment.** 

```
opencensus==0.7.7
opencensus-ext-jaeger==0.7.1
opencensus-ext-zipkin==0.2.2
```

Running jaeger all in one with zipkin enabled:
```
  jaeger:
    image: jaegertracing/all-in-one:1.17
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775"
      - "6831"
      - "6832"
      - "5778"
      - "16686:16686"
      - "14268:14268"
      - "14250"
      - "9411:9411"
```

**Steps to reproduce.**

Using tracer with collector endpoint:
`JaegerExporter(service_name='my-service', host_name='localhost', port=14268)`
causes: EOFError (caught here: https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-jaeger/opencensus/ext/jaeger/trace_exporter/__init__.py#L382 - which is not printed due to lack of str() and message interpretation).

It seems that for whatever reason, I am getting: 400 Bad Request from jaeger. 

`ZipkinExporter(service_name='my-service', host_name='localhost', port=9411)`
works just fine with same setup.
